Description: Base System
Name: base
Packages:
- bash
- coreutils
- rpm
- udev
- tizen-release
- filesystem
- prelink
- readline
- setup
- passwd
- procps
- login
- util-linux-ng
- e2fsprogs
- net-tools
- psmisc
- module-init-tools
- cpio
- gawk
- sed
- tar
- gzip
- grep
- bzip2
- binutils
- alsa-utils
- mtdev
- bluez
- less
- connman
- syslinux
- tizen-repos
- insserv
- mingetty
- sysvinit
- mkdevnodes
- dlogutil
- audio-session-manager
- lsb
- drm-service
- cert-svc
- bluez-gstreamer
- sensor-framework
- libss-client
- ss-server
- libsqlfs
- tzdata-slp
- sysvinit-utils
- rfkill
- ofono
- bluetooth-frwk
- bluetooth-frwk-agent
- sonet
- usbutils
Summary: Base System
